# Generated by Django 3.2.6 on 2021-08-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('mobile', models.IntegerField(max_length=10, unique=True)),
                ('age', models.IntegerField(max_length=3)),
                ('blood_group', models.CharField(max_length=3)),
            ],
        ),
    ]
